name: Create a bucket for the PR

on:
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  create_env:
    name: Create S3 bucket on Cellar
    runs-on: ubuntu-latest
    steps:
      - name: Set key id
        run: aws configure set aws_access_key_id ${{ secrets.CELLAR_ADDON_KEY_ID }}
      - name: Set secret key
        run: aws configure set aws_secret_access_key ${{ secrets.CELLAR_ADDON_KEY_SECRET }}
      - name: Create bucket
        run: aws s3api create-bucket --bucket ${{github.head_ref}} --acl public-read --endpoint-url ${{ secrets.CELLAR_ADDON_HOST }} > /dev/null
