name: Deploy review in a bucket

on:
  pull_request

jobs:
  build:
    name: Build & deploy Gatsby site
    runs-on: ubuntu-20.04
    steps:
      - name: Define subdomain
        id: subdomain-generator
        run: echo "::set-output name=subdomain::$(echo ${{ github.head_ref }} |
          sed 's/[^a-zA-Z0-9]//g' |
          tr '[:upper:]' '[:lower:]')-review"
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies & build
        run: |
          yarn install
          yarn build
      - name: Add robots.txt
        run: |
          echo "User-agent: *\nDisallow: /" > ./public/robots.txt

      - name: Deploy on S3 bucket
        run: |
          aws configure set aws_access_key_id ${{secrets.CELLAR_ADDON_KEY_ID}}
          aws configure set aws_secret_access_key ${{secrets.CELLAR_ADDON_KEY_SECRET}}
          aws configure set region ${{ secrets.CELLAR_ADDON_REGION }}
          aws s3 sync ./public s3://${{ steps.subdomain-generator.outputs.subdomain }}.${{ secrets.DOMAIN_NAME }} --endpoint-url https://${{ secrets.CELLAR_ADDON_HOST }} --acl public-read
