name: Deploy review in a bucket

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build & deploy Gatsby site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install dependencies & build
        run: |
          yarn install
          yarn build
      - name: Deploy on S3 bucket
        run: |
          aws configure set aws_access_key_id ${{ secrets.CELLAR_ADDON_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.CELLAR_ADDON_KEY_SECRET }}
          aws s3 sync ./public/ s3://${{github.head_ref}} --endpoint-url ${{ secrets.CELLAR_ADDON_HOST }} --acl public-read
